### ISSUE TITLE
Stock card autoexpands when dragging on some screens

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#716] opened 2016-03-22 11:51 UTC
On some screens (Lenovo Yoga) the stock card just keeps expanding. This makes it impossible to demo on some of our sales people laptops!

![image](https://cloud.githubusercontent.com/assets/9947570/13950666/471bad6c-f024-11e5-9745-0841b8d55c91.png)

It happens with the touch screen on and off.

**Comment by bjedrzejewski** [comment] 2016-03-22 12:11
It does work on MS Surface. So it is not strictly touchscreens related.

**Comment by WPFerg** [comment] 2016-03-22 12:17
From the config file:
```
maxWidth: 230,
maxHeight: 100,
```
Weird.

**Comment by bjedrzejewski** [comment] 2016-03-22 12:18
The problem gets worse when you move the mouse- any ideas? What happens on drag?

Also, we replicated it on another Lenovo Yoga.

**Comment by bjedrzejewski** [comment] 2016-03-22 12:35
Not sure if related, I found that on localhost:9090

TypeError: Cannot read property 'open' of undefined
    at app.js:1
    at whenReady (<anonymous>:2543:9)
    at Object.fin.desktop.main (<anonymous>:2601:5)
    at Object.d [as ready] (app.js:1)
    at a._createClass.value (app.js:1)
    at app.js:1
    at m.$digest (angular.min.js:139)
    at m.$apply (angular.min.js:142)
    at g (angular.min.js:94)
    at x (angular.min.js:98)(anonymous function) @ angular.min.js:114

**Comment by akhmorgan** [comment] 2016-03-30 10:54
Tested on the Lenovo Yoga, and the issue appears to be tied to the display settings. The System display setting for the size of text, apps and other items is set to 150% as the default, recommended setting. Changing this to 100% removes the issue.

**Comment by akhmorgan** [comment] 2016-03-30 11:02
Adjusting display settings on a desktop to change the size of text and other items to 150%, produces the same bug.

**Comment by akhmorgan** [comment] 2016-03-31 08:45
The issue is not present at 125% scale.

**Comment by akhmorgan** [comment] 2016-03-31 10:46
The issue appears to be related to the use of `window.moveTo`

**Comment by akhmorgan** [comment] 2016-04-05 10:58
A stopgap fix has been implemented by repeatedly setting the bounds on the tearout, pending further investigation into the root cause of the issue, which may be outside of the scope of this app.

**Closed by akhmorgan** 2016-04-05 10:58 UTC
Labels: bug
