### ISSUE TITLE
You can drag a stock into a window that is behind the main one.

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#555] opened 2016-03-07 14:21 UTC
With the following configuration, if I drag the 'YUM' tile to the right of the favourites pane I would expect it to create a new window:

![image](https://cloud.githubusercontent.com/assets/1098110/13571955/ae0e9b94-e46f-11e5-8266-60d2d0c28ea8.png)

However, the tear-out logic determines that it intersects with the window underneath, causing it to be added to its list of stocks.

Confusing!

**Comment by owennw** [comment] 2016-03-07 14:28
While I agree that it is confusing, I don't think there's much we can do about it at the moment (see #359).

**Comment by owennw** [comment] 2016-03-08 14:50
Dupe of #359

**Closed by owennw** 2016-03-08 14:50 UTC
Labels: bug, wontfix
