### ISSUE TITLE
Resizing issues when restoring as compact window after restart.

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#647] opened 2016-03-15 16:03 UTC
When window is restored as compact (restarting the app) and then made not compact, resizing doesn't work.

**Comment by WPFerg** [comment] 2016-03-15 16:07
Copying this from #619, as it seems to fit here:
This seems to be part of a larger issue, in that without that code to do that, a window created in compact and then expanded is not resizable.
Having a further look at the information passed to openfin, via: `_window.updateOptions(newOptions, cb)`, where `cb` is:
```js
() => {
    _window.getOptions((opts) => {
        console.log('got opts', opts);
    });
};
```
Openfin outputs this state for when the window is *not* compact, ie. that it *should* be resizable: `
resizable: true`. However, it is not resizable.
 I feel this is going to be a `wontfix`, but if anyone else has any ideas, please share

**Comment by WPFerg** [comment] 2016-03-22 09:14
Having a further play around with this, I can't reproduce the behaviour on a sample non-Stockflux app, so I'm unsure how to proceed.

**Comment by owennw** [comment] 2016-03-22 09:21
That would indicate that the bug is in our code then?

**Closed** 2016-03-23 12:41 UTC
Labels: bug
