### ISSUE TITLE
Allow tearing out the last (single) fav- this should close the remaining window perhaps?

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#410] opened 2016-02-23 14:41 UTC

**Comment by owennw** [comment] 2016-02-23 14:42
#311

**Comment by bjedrzejewski** [comment] 2016-02-23 14:52
@owennw but... why? I though this is a rather natural thing to do. I do it all the time on chrome (merge a single tab window into multi tab window, by tearout).

**Comment by rmarcalo** [comment] 2016-03-10 14:15
I think the long-term ideal solution is to allow tear out and then merge within a new window. If this is not yet possible, then disabling the tear-out makes more sense.

**Comment by ColinEberhardt** [comment] 2016-04-22 08:38
Duplicate of https://github.com/ScottLogic/StockFlux/issues/726

**Closed by ColinEberhardt** 2016-04-22 08:38 UTC
Labels: question
