### ISSUE TITLE
Upgrade version of OpenFin to 13 (Latest stable)

### ISSUE THREAD

**Issue by jrhenderson1988** [ScottLogic/StockFlux#1233] opened 2019-07-24 08:27 UTC
Upgrade to 13 when it is really stable and `getWebWindow` does not fail anymore.

Investigate the use of 14 (beta when available)

**Comment by SL-SWoods** [comment] 2019-12-04 15:04
Closing as duplicate of #1390

**Closed by SL-SWoods** 2019-12-04 15:04 UTC
Labels: OpenFin
