### ISSUE TITLE
UX Issues [Compact View]

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#496] opened 2016-03-03 08:30 UTC
- [x] Application version doesn’t need, in my opinion, to be shown in the small version. It’s a hidden information that serves as a distraction when placed on the search bar (and has no other space to be).
- [x] Size of Closed Windows icon does not fit the remaining icons, it should be increased by a few px diagonally (can’t inspect element to test it myself).

Removed for #464
~~*Quite a big one, so it can be moved into its own issue if need be:*~~
~~- [ ] If a detached card window is moved on top of another one, it should integrate into it, with it’s cards moved to the bottom of the list (maintaining their order).~~

**Comment by owennw** [comment] 2016-03-03 11:03
Point 3 is a dupe of #464, which I think would be a v2 feature.

**Comment by owennw** [comment] 2016-03-03 16:14
Closed by #495

**Closed by owennw** 2016-03-03 16:14 UTC
Labels: bug, Compact View, style
